# Définition des ingress pour le path /, la liste des hosts est défini dans le repo de déploiment

ingress:
  baseDomain: ".fr"
  hosts:
    - host: maazi-front

image:
  repository: rg.fr-par.scw.cloud/mazi/masi-front
  tag: 0.8.7


# Déterminer le nombre de replicas du même pod que l'on souhaite
replicas: 1

# Choisir un issuer pour la création de certificats tls
certManagerIssuer: letsencrypt

ingressClassName: "public"

env:
  secretEnv: