ingress:
  baseDomain: ".maazi.fr"
  hosts:
    - host: www

# root domain dont les requêtes seront redirigées sur www.maazi.fr => est inclu dans le certificat TLS
rootHost: maazi.fr 

image:
  repository: rg.fr-par.scw.cloud/mazi/masi-front
  tag: 0.8.7


# Déterminer le nombre de replicas du même pod que l'on souhaite
replicas: 1

# Choisir un issuer pour la création de certificats tls
certManagerIssuer: letsencrypt

ingressClassName: "public"

config: